version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sunrin_pass_db_dev
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: always
    networks:
      - sunrin_pass_dev
    command: postgres -c 'max_connections=1000'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: sunrin_pass_pgadmin_dev
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    networks:
      - sunrin_pass_dev
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data_dev:
    name: sunrin_pass_postgres_data_dev
  pgadmin_data_dev:
    name: sunrin_pass_pgadmin_data_dev

networks:
  sunrin_pass_dev:
    name: sunrin_pass_network_dev
    driver: bridge
